abbr -a ls  "exa --group-directories-first"
abbr -a ll  "exa -la --git --group-directories-first"
abbr -a cat "bat"
abbr -a q   "exit"
abbr -a dcup "docker compose up -d && docker compose logs -f"
abbr -a ts 'tmux new -s $(basename $(pwd))'
abbr -a ta 'tmux attach'
abbr -a cw 'cargo watch - '
abbr -a v 'nvim'
abbr -a tree  "exa -la --git --git-ignore --group-directories-first --tree"
abbr -a dps 'docker ps --format "table {{.ID}}\t{{.Names}}\t{{.RunningFor}}\t{{.Status}}"'
abbr -a dcps 'docker compose ps --format "table {{.ID}}\t{{.Names}}\t{{.RunningFor}}\t{{.Status}}"'
abbr -a fn 'find . -name '

abbr -a gs 'git status'
abbr -a gd 'git diff'
abbr -a gp 'git push'
abbr -a gc 'git commit -m'
abbr -a gca 'git commit --amend'

abbr -a clera 'clear'
abbr -a claer 'clear'
abbr -a clare 'clear'
abbr -a clrea 'clear'
abbr -a clrae 'clear'
abbr -a celra 'clear'
abbr -a celar 'clear'
abbr -a cearl 'clear'
abbr -a cealr 'clear'
abbr -a ceral 'clear'
abbr -a cerla 'clear'
abbr -a caler 'clear'
abbr -a calre 'clear'
abbr -a caelr 'clear'
abbr -a caerl 'clear'
abbr -a carle 'clear'
abbr -a carel 'clear'
abbr -a crlae 'clear'
abbr -a crlea 'clear'
abbr -a creal 'clear'
abbr -a crela 'clear'
abbr -a crael 'clear'
abbr -a crale 'clear'
abbr -a lcrea 'clear'
abbr -a lcrae 'clear'
abbr -a lcera 'clear'
abbr -a lcear 'clear'
abbr -a lcare 'clear'
abbr -a lcaer 'clear'
abbr -a lerac 'clear'
abbr -a lerca 'clear'
abbr -a lecar 'clear'
abbr -a lecra 'clear'
abbr -a leacr 'clear'
abbr -a learc 'clear'
abbr -a larce 'clear'
abbr -a larec 'clear'
abbr -a lacre 'clear'
abbr -a lacer 'clear'
abbr -a laerc 'clear'
abbr -a laecr 'clear'
abbr -a lraec 'clear'
abbr -a lrace 'clear'
abbr -a lrcea 'clear'
abbr -a lrcae 'clear'
abbr -a lreca 'clear'
abbr -a lreac 'clear'
abbr -a ecarl 'clear'
abbr -a ecalr 'clear'
abbr -a ecral 'clear'
abbr -a ecrla 'clear'
abbr -a eclar 'clear'
abbr -a eclra 'clear'
abbr -a elacr 'clear'
abbr -a elarc 'clear'
abbr -a elrca 'clear'
abbr -a elrac 'clear'
abbr -a elcra 'clear'
abbr -a elcar 'clear'
abbr -a ealrc 'clear'
abbr -a ealcr 'clear'
abbr -a earlc 'clear'
abbr -a earcl 'clear'
abbr -a eaclr 'clear'
abbr -a eacrl 'clear'
abbr -a erlca 'clear'
abbr -a erlac 'clear'
abbr -a eracl 'clear'
abbr -a eralc 'clear'
abbr -a ercal 'clear'
abbr -a ercla 'clear'
abbr -a acler 'clear'
abbr -a aclre 'clear'
abbr -a acelr 'clear'
abbr -a acerl 'clear'
abbr -a acrle 'clear'
abbr -a acrel 'clear'
abbr -a alcre 'clear'
abbr -a alcer 'clear'
abbr -a alerc 'clear'
abbr -a alecr 'clear'
abbr -a alrec 'clear'
abbr -a alrce 'clear'
abbr -a aeclr 'clear'
abbr -a aecrl 'clear'
abbr -a aelcr 'clear'
abbr -a aelrc 'clear'
abbr -a aercl 'clear'
abbr -a aerlc 'clear'
abbr -a arcel 'clear'
abbr -a arcle 'clear'
abbr -a arlec 'clear'
abbr -a arlce 'clear'
abbr -a arelc 'clear'
abbr -a arecl 'clear'
abbr -a rcale 'clear'
abbr -a rcael 'clear'
abbr -a rclae 'clear'
abbr -a rclea 'clear'
abbr -a rceal 'clear'
abbr -a rcela 'clear'
abbr -a rlaec 'clear'
abbr -a rlace 'clear'
abbr -a rlcea 'clear'
abbr -a rlcae 'clear'
abbr -a rleca 'clear'
abbr -a rleac 'clear'
abbr -a reacl 'clear'
abbr -a realc 'clear'
abbr -a recal 'clear'
abbr -a recla 'clear'
abbr -a relac 'clear'
abbr -a relca 'clear'
abbr -a raelc 'clear'
abbr -a raecl 'clear'
abbr -a racle 'clear'
abbr -a racel 'clear'
abbr -a ralce 'clear'
abbr -a ralec 'clear'
