local builtin = require('telescope.builtin')
local telescope = require("telescope")
telescope.load_extension('harpoon')
vim.keymap.set('n', '<leader>f', builtin.find_files, {})
vim.keymap.set('n', '<leader>gg', builtin.live_grep, {})
